apiVersion: v1
kind: Service
metadata:
  name: owncloud-mysql
  labels:
    app: owncloud
spec:
  ports:
    - port: 3306
  selector:
    app: owncloud
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: owncloud-mysql
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: owncloud
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: efs-mysql
